const START = '<!-- solstack:start -->';
const END = '<!-- solstack:end -->';
const NOTE = '<!-- Generated by solstack. Edit outside these markers; `solstack update` rewrites what is inside. -->';

/**
 * Inserts or replaces solstack's section in a Markdown file, leaving everything outside the markers alone.
 * Passing `null` removes the section.
 */
export function upsertManagedBlock(existing: string | null, body: string | null): string {
  const current = existing ?? '';
  const start = current.indexOf(START);
  const end = current.indexOf(END);
  const hasBlock = start !== -1 && end > start;
  const block = body === null ? '' : `${START}\n${NOTE}\n${body.trim()}\n${END}`;

  if (hasBlock) {
    const before = current.slice(0, start);
    const after = current.slice(end + END.length);
    if (body === null) return `${before.trimEnd()}\n${after.trimStart()}`.trim() + (before.trim() || after.trim() ? '\n' : '');
    return `${before}${block}${after}`;
  }
  if (body === null) return current;
  return current.trim() ? `${current.trimEnd()}\n\n${block}\n` : `${block}\n`;
}

export type Json = Record<string, unknown>;

export function parseJsonObject(text: string | null): Json | null {
  if (text === null || !text.trim()) return {};
  try {
    const value: unknown = JSON.parse(text);
    return value && typeof value === 'object' && !Array.isArray(value) ? (value as Json) : null;
  } catch {
    return null;
  }
}

function child(object: Json, key: string): Json {
  const value = object[key];
  return value && typeof value === 'object' && !Array.isArray(value) ? (value as Json) : {};
}

/** Sets `object[group][name] = value`, keeping every other entry. */
export function setEntry(object: Json, group: string, name: string, value: unknown): Json {
  return { ...object, [group]: { ...child(object, group), [name]: value } };
}

/** Removes `object[group][name]`, dropping `group` if nothing else is left in it. */
export function removeEntry(object: Json, group: string, name: string): Json {
  const entries = { ...child(object, group) };
  delete entries[name];
  const result = { ...object };
  if (Object.keys(entries).length) result[group] = entries;
  else delete result[group];
  return result;
}
